### ISSUE TITLE
Dominio http://rubyni.com/ caído

### ISSUE THREAD

**Issue by paulomcnally** [rubyni/rubyni.github.com#6]
El dominio está caído. @eveevans @g3ortega 

![Imgur](http://i.imgur.com/lwbN3fQ.png)

Saludos

**Comment by manueltorrez** [comment]
El dominio expiró <a href="http://tinypic.com?ref=2mdsdcg" target="_blank"><img src="http://i66.tinypic.com/2mdsdcg.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by eveevans** [comment]
No habia visto. 
Voy a revisar.

**Comment by paulomcnally** [comment]
@eveevans no te hace click que nos movamos para conseguir ruby.ni o ruby.com.ni?

Que opinan los demás miembros de la comunidad?

**Comment by leogg** [comment]
ruby.org.ni sería lo ideal... te lo pueden patrocinar en el nic.ni

**Comment by paulomcnally** [comment]
@leogg con quien hay que hablar en el nic.ni? Me interesa también para otra comunidad.

**Comment by leogg** [comment]
@paulomcnally Podés probar con Marvin Castañeda <marvin@nic.ni> o Marvin Rosales <santos@nic.ni>

**Comment by paulomcnally** [comment]
Gracias @leogg

**Comment by paulomcnally** [comment]
> Your message wasn't delivered to santos@nic.ni because the address couldn't be found. Check for typos or unnecessary spaces and try again.

> Your message wasn't delivered to marvin@nic.ni because the address couldn't be found. Check for typos or unnecessary spaces and try again.

Al parecer no existe el correo de ambos.

**Comment by eveevans** [comment]
De acuerdo,  hace más sentido estuviera en Nic.ni

Lo único que me preocupa es que son bien famosos por ser bastantes burocraticos y lentos. 
Y si eso va a ser mas problema, mejor se compra nuevamente el rubyni.com 

Que piensan ?

**Comment by paulomcnally** [comment]
El otro día estaba en el nic.ni (oficina) y vi que en cuestión de 20 minutos despacharon a unas chicas que llegaron a comprar su dominio, hasta con correos configurados y todo.

**Comment by eveevans** [comment]
Si es así, intentemos con Nic.ni

@g3ortega  @hanselmw  ?

**Comment by leogg** [comment]
@paulomcnally Nelson Juarez <admin@nic.ni> https://www.linkedin.com/in/nelson-juarez-100808b2

Sería bueno una carta explicando lo que es la comunidad y solicitando el apoyo.

**Comment by hanselmw** [comment]
No he tenido de las mejores experiencias con Nic.ni, pero
no veo por que no intentar obtener el org.ni .

**Comment by eveevans** [comment]
@leogg gracias por el consejo. 
Ya que esos dos correos, no funcionan, ¿Sabés a quién se le puede escribir para hacer esta solicitud ? 

@paulomcnally  gracias por estar pendiente. 
Mmm, me gustaria probar con el encargado de esto, antes de escribirle al director (No creo que nos haga mucho caso si no le compete)

**Comment by leogg** [comment]
@eveevans La gente del nic.ni es bastante accesible. Si les explican que es un proyecto de una comunidad de software libre no tienen problemas en darles el dominio. Los contactos que yo tenía aparentemente se fueron hace años, pero valdría la pena darse una vuelta por ahí y preguntar.

**Comment by eveevans** [comment]
El dominio está en redemptionPeriod. 
Supongo que simplemente podemos recomprarlo en un par de dias :p
```

   Domain Name: RUBYNI.COM
   Registry Domain ID: 1733345210_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.tucows.com
   Registrar URL: http://www.tucowsdomains.com
   Updated Date: 2017-08-22T06:31:08Z
   Creation Date: 2012-07-12T03:40:57Z
   Registry Expiry Date: 2017-07-12T03:40:57Z
   Registrar: Tucows Domains Inc.
   Registrar IANA ID: 69
   Registrar Abuse Contact Email:
   Registrar Abuse Contact Phone:
   Domain Status: redemptionPeriod https://icann.org/epp#redemptionPeriod
   Name Server: NS1.MEDIATEMPLE.NET
   Name Server: NS2.MEDIATEMPLE.NET
   DNSSEC: unsigned
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2017-09-19T20:54:39Z <<<
```

**Comment by g3ortega** [comment]
El dominio està de nuevo funcionando 😃 

Voy a sacar un tiempito està semana para hacerle algunos retoques al sitio, y quizà agregar algo de contenido

**Comment by eveevans** [comment]
Vos lo compraste/configuraste ? 
Seria bueno hacer una lista de objetivos y planes para el sitio, asi otros pueden colaborar tambien.
