### ISSUE TITLE
Links del blog en Disqus están rotos

### ISSUE THREAD

**Issue by manueltorrez** [rubyni/rubyni.github.com#8]
Los links de los comentarios en Disqus redirigen a un enlace como este: `http://0.0.0.0:4000/2014/08/05/redisenio-del-sitio/`

**Comment by eveevans** [comment]
Gracias @manueltorrez  
Vamos a revisar.

**Comment by eveevans** [comment]
Ya vi, hay 2 issues: 
1. Hay un conflicto entre disqus y las URLs de jekyll  (Ya enviado commit) 
2. Habian par de comentarios de prueba que se metian dentro del feed de comentarios (En proceso de migracion)

**Comment by eveevans** [comment]
Solucionado. 
Gracias por el reporte.
